spring.application.name=DiaryApp
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/practice
spring.datasource.username = postgres
spring.datasource.password = 0000